### ndarray 정렬

In [1]:
import numpy as np

##### 1차원 배열 정렬

In [22]:
arr = np.random.randint(1, 11, 10)
arr

array([ 8,  2,  1,  9,  4, 10,  5,  6,  5,  2], dtype=int32)

In [ ]:
# np.sort(arr) : 정렬된 ndarray를 반환
print(np.sort(arr))
print(arr)

[ 1  2  2  4  5  5  6  8  9 10]
[ 8  2  1  9  4 10  5  6  5  2]


---

##### 2차원 배열 정렬

In [25]:
arr = np.random.randint(10, size=(3, 4))  # 0 이상 10 미만
arr

array([[2, 1, 4, 8],
       [3, 0, 7, 6],
       [6, 6, 1, 7]], dtype=int32)

In [26]:
np.sort(arr)

array([[1, 2, 4, 8],
       [0, 3, 6, 7],
       [1, 6, 6, 7]], dtype=int32)

In [28]:
print(np.sort(arr, axis=0)) # 행 방향 정렬(같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬(같은 행 안에서 정렬)

[[2 0 1 6]
 [3 1 4 7]
 [6 6 7 8]]
[[1 2 4 8]
 [0 3 6 7]
 [1 6 6 7]]


In [ ]:
print(np.sort(arr, axis=None))  # axis=None 축 무시(행/열 구분 없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 1 1 2 3 4 6 6 6 7 7 8]


##### np.argsort
- 배열의 값을 정렬 했을때, 원래의 인덱스값을 반환한다.
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스값을 반환

In [32]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [43]:
names = np.array(["리사", "로제", "제니", "지수"])
album_sales = np.array([900, 870, 1000, 670])

print(np.sort(album_sales)[::-1])
print(np.argsort(album_sales)[::-1])

sales_desc = np.argsort(album_sales)[::-1]
names[sales_desc]

[1000  900  870  670]
[2 0 1 3]


array(['제니', '리사', '로제', '지수'], dtype='<U2')

In [ ]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 2, 28], [17, 18, 30]])

print(np.argsort(arr))
print(np.argsort(arr, axis=1))  # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0))  # 행 방향 정렬의 순서 (같은 열 안에서 정렬)